CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220818071814_InitialSchema') THEN
    CREATE TABLE "bqz_ExecutionLogs" (
        "LogId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RunInstanceId" character varying(256) NULL,
        "LogType" varchar(20) NOT NULL,
        "JobName" character varying(256) NULL,
        "JobGroup" character varying(256) NULL,
        "TriggerName" character varying(256) NULL,
        "TriggerGroup" character varying(256) NULL,
        "ScheduleFireTimeUtc" timestamp with time zone NULL,
        "FireTimeUtc" timestamp with time zone NULL,
        "JobRunTime" interval NULL,
        "RetryCount" integer NULL,
        "Result" character varying(8000) NULL,
        "ExceptionMessage" text NULL,
        "ExecutionDetails" text NULL,
        "IsVetoed" boolean NULL,
        "IsException" boolean NULL,
        "DateAddedUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_bqz_ExecutionLogs" PRIMARY KEY ("LogId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220818071814_InitialSchema') THEN
    CREATE INDEX "IX_bqz_ExecutionLogs_DateAddedUtc_LogType" ON "bqz_ExecutionLogs" ("DateAddedUtc", "LogType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220818071814_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_bqz_ExecutionLogs_RunInstanceId" ON "bqz_ExecutionLogs" ("RunInstanceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220818071814_InitialSchema') THEN
    CREATE INDEX "IX_bqz_ExecutionLogs_TriggerName_TriggerGroup_JobName_JobGroup~" ON "bqz_ExecutionLogs" ("TriggerName", "TriggerGroup", "JobName", "JobGroup", "DateAddedUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20220818071814_InitialSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20220818071814_InitialSchema', '6.0.8');
    END IF;
END $EF$;
COMMIT;

